[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32H7S3L8Hx --probe 0483:3754:004F00203033510135393935'

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "trace"
